name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  lucide_icons_flutter: ^3.1.1
  permission_handler: ^12.0.1
  carousel_slider: ^5.1.1
  image_picker: ^1.2.0
  connectivity_plus: ^7.0.0
  url_launcher: ^6.3.2
  share_plus: ^12.0.0
  geolocator: ^14.0.2
  sms_autofill: ^2.3.0
  pin_code_fields: ^8.0.1
  package_info_plus: ^8.3.1
  lottie: ^3.3.2
  get: ^4.7.2
  get_storage: ^2.1.1
  flutter_svg: ^2.2.1
  shared_preferences: ^2.5.3
  font_awesome_flutter: ^10.10.0
  google_maps_flutter: ^2.13.1
  geocoding: ^4.0.0
  webview_flutter: ^4.13.0
  photo_view: ^0.15.0
  flutter_html: ^3.0.0
  flutter_pdfview: ^1.4.3
  path_provider: ^2.1.5
  printing: ^5.14.2
  flutter_rating: ^2.0.2
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.5.0
  firebase_core: ^4.2.0
  google_maps_flutter_android: ^2.18.4
  timeago: ^3.7.1
  animated_splash_screen: ^1.3.0

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/
    - assets/animations/

  fonts:
    - family: NotoKufiArabic
      fonts:
        - asset: assets/fonts/NotoKufiArabic-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoKufiArabic-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoKufiArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoKufiArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoKufiArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoKufiArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoKufiArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoKufiArabic-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoKufiArabic-Black.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900